"""Claude Code environment construction: env vars (mirroring FreeToken's
proven `ft launch claude` mapping, with ANTHROPIC_BASE_URL pointed at the
capture proxy), an isolated per-task CLAUDE_CONFIG_DIR, and the task prompt.
"""
from __future__ import annotations

import json
import logging
import os
from pathlib import Path

from .config import Config

log = logging.getLogger("claude_env")

# Env vars never inherited from the caller (avoid leaking real credentials /
# endpoints into the collection environment).
DROP_ENV_PREFIXES = ("ANTHROPIC_", "OPENAI_", "CLAUDE_", "GEMINI_", "MCP_")
KEEP_ENV = ("PATH", "HOME", "LANG", "LC_ALL", "TERM", "TMPDIR", "USER",
            "LOGNAME", "SHELL", "SSH_CONNECTION", "LD_LIBRARY_PATH")


def build_prompt(task: dict, include_interface: bool = False) -> str:
    issue = str(task.get("problem_statement") or "").strip()
    parts = [
        "You are Claude Code working on a real software engineering task.",
        "",
        "The following is a real issue from this repository's tracker. The repo",
        "is checked out at a specific historical commit, so some surrounding",
        "code may look different from today's version.",
        "",
        "<issue>",
        issue,
        "</issue>",
        "",
    ]
    if include_interface and task.get("interface"):
        parts += ["<additional_interface_notes>", str(task["interface"]).strip(), "</additional_interface_notes>", ""]
    parts += [
        "Goal: diagnose the issue and implement a fix in this repository.",
        "",
        "Guidelines:",
        "- Plan first: explore the repository and understand the relevant code paths",
        "  before making any edits.",
        "- Use the Task tool to dispatch subagents for independent, parallelizable",
        "  investigation (for example: one subagent to locate the faulty code path,",
        "  another to survey the related tests). Integrate their reports before you",
        "  start editing.",
        "- Implement the fix, then verify it by running the project's tests where the",
        "  environment allows.",
        "- Do not commit or push; leave your changes in the working tree.",
        "",
    ]
    return "\n".join(parts)


def _clean_base_env(cfg: Config) -> dict:
    env = {k: v for k, v in os.environ.items()
           if k in KEEP_ENV or not k.startswith(DROP_ENV_PREFIXES)}
    claude_dir = str(Path(cfg.claude_bin).parent)
    env["PATH"] = claude_dir + os.pathsep + env.get("PATH", "/usr/bin:/bin")
    return env


def seed_config_dir(config_dir: Path) -> None:
    config_dir.mkdir(parents=True, exist_ok=True)
    claude_json = config_dir / ".claude.json"
    if not claude_json.exists():
        claude_json.write_text(json.dumps({
            "hasCompletedOnboarding": True,
            "bypassPermissionsModeAccepted": True,
            "theme": "dark",
            "autoUpdates": False,
        }, indent=1), encoding="utf-8")
    settings = config_dir / "settings.json"
    if not settings.exists():
        settings.write_text("{}\n", encoding="utf-8")


def build_task_env(cfg: Config, task_dir: Path) -> dict:
    """Returns the env dict for the claude process and writes task_dir/env.sh."""
    config_dir = task_dir / "claude_config"
    seed_config_dir(config_dir)

    env = _clean_base_env(cfg)
    served = cfg.served_model_name
    env.update({
        "ANTHROPIC_BASE_URL": cfg.proxy_base,
        "ANTHROPIC_API_KEY": "sk-freetoken-local",
        "ANTHROPIC_AUTH_TOKEN": "sk-freetoken-local",
        "ANTHROPIC_MODEL": served,
        "ANTHROPIC_DEFAULT_SONNET_MODEL": served,
        "ANTHROPIC_DEFAULT_OPUS_MODEL": served,
        "ANTHROPIC_DEFAULT_HAIKU_MODEL": served,
        "ANTHROPIC_SMALL_FAST_MODEL": served,
        "CLAUDE_CODE_SUBAGENT_MODEL": served,
        "CLAUDE_CODE_MAX_CONTEXT_TOKENS": str(cfg.max_context_tokens),
        "CLAUDE_CODE_MAX_OUTPUT_TOKENS": str(cfg.max_output_tokens),
        "CLAUDE_CODE_ATTRIBUTION_HEADER": "0",
        "CLAUDE_CONFIG_DIR": str(config_dir),
        "API_TIMEOUT_MS": str(cfg.api_timeout_ms),
        "DISABLE_AUTOUPDATER": "1",
        "DISABLE_TELEMETRY": "1",
        "DISABLE_ERROR_REPORTING": "1",
        "DISABLE_BUG_COMMAND": "1",
    })

    lines = ["#!/usr/bin/env bash", "# auto-generated by claude_env.build_task_env"]
    for k, v in env.items():
        if k in KEEP_ENV and k != "PATH":
            continue
        lines.append(f"export {k}={json.dumps(v)}")  # json string == safe shell single token
    (task_dir / "env.sh").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return env
